// LocalStorage Variables
export const LOCAL_STORAGE = '@QYON-XML/'

export const TOKEN_STORAGE = LOCAL_STORAGE + 'TOKEN'
export const THEME_STORAGE = LOCAL_STORAGE + 'THEME'
export const DOMAIN_STORAGE = LOCAL_STORAGE + 'DOMAIN'
export const DOMAIN_INFORMATION_STORAGE = LOCAL_STORAGE + 'DOMAIN_INFORMATION'
export const USER_STORAGE = LOCAL_STORAGE + 'USER'
export const USER_INFORMATION_STORAGE = LOCAL_STORAGE + 'USER_INFORMATION'
